name: Backend CI

on:
  pull_request:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/backend-ci.yml'
      - '!**.md'

jobs:
  backend-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Check Code Formatting (Spotless)
        run: mvn spotless:check

      - name: Check Code Quality (Checkstyle)
        run: mvn checkstyle:check

      - name: Find Bugs (SpotBugs)
        run: mvn spotbugs:check

      - name: Run Unit Tests and SonarCloud Analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=AnthonyChing_performance-management-system -Dsonar.organization=anthonyching -Dsonar.host.url=https://sonarcloud.io
