name: Build and deploy frontend

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend.yml'
      - '!**.md'

jobs:
  frontend_pass_check:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./frontend

    steps:
      - uses: actions/checkout@v4

      - name: Do nothing
        run: echo "Workflow passes without doing anything"
    
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: ./frontend/package.json
        
      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npm run test:e2e

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: frontend/playwright-report/
          retention-days: 14


# jobs:
#   deploy:
#     runs-on: self-hosted
#     concurrency:
#       group: frontend-deploy
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v6
#       - name: Build Docker image
#         run: |
#           docker build \
#             -t frontend:${{ github.sha }} \
#             -t frontend:latest \
#             ./frontend
#       - name: Run Docker container
#         run: |
#           docker stop frontend || true
#           docker rm frontend || true
#           docker run -d \
#             --name frontend \
#             -p 80:80 \
#             --network cspace_network \
#             --restart unless-stopped \
#             frontend:${{ github.sha }}
